import type { Metadata } from 'next';
import './globals.css';
import AppProviders from '@/providers';

export const metadata: Metadata = {
  title: 'Peerby',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        {/* Link to the manifest */}
        <link rel="manifest" href="/manifest.json" />
        {/* Theme color */}
        <meta name="theme-color" content="#000000" />
        {/* Favicon links */}
        <link rel="icon" href="/assets/icons/icon512_rounded.png" />
        <link rel="icon" href="/assets/icons/icon512_rounded.png" sizes="512x512" />
      </head>
      <body className={`antialiased`} style={{ fontFamily: 'IranSans' }}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
