import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import SessionProvider from "@/providers/session-provider";
import DirectionProvider from "@/providers/direction-provider";
import ToastifyProvider from "@/providers/toastify-provider";
import StoreProvider from "@/providers/store-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <link rel="icon" href="/assets/icons/icon512_rounded.png" />
        <link rel="icon" href="/assets/icons/icon512_rounded.png" sizes="512x512" />
      </head>
      <body className={`antialiased`} style={{ fontFamily: "IranSans" }}>
        <DirectionProvider>
          <ToastifyProvider />
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <SessionProvider>
              <StoreProvider>{children}</StoreProvider>
            </SessionProvider>
          </ThemeProvider>
        </DirectionProvider>
      </body>
    </html>
  );
}
